name: Developer Tests

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  launch-tests:
    runs-on: ubuntu-latest
    container: openjdk:21-ea-1-jdk

    steps:
      - uses: actions/checkout@v4

      - name: Show repo structure
        run: |
          pwd
          ls
          ls p2-todolist-app

      - name: Launch tests with Maven
        run: |
          cd p2-todolist-app
          chmod +x mvnw
          ./mvnw test